global:
  total_training_steps: 5000                         # Total gradient updates to perform
  save_interval_steps: 1000                          # How often to backup the "best_model.pth" and replay buffer
  logging_rotation_steps: 1000                       # How often to make a new log folder
  min_buffer_size: 1024000                           # Minimum Replay Buffer Size
  max_buffer_size: 8192000                           # Max buffer size
  buffer_ramp_steps: 10000                           # Steps to reach max buffer size
  hdf5_chunk_size: 16                                # HDF5 storage chunking. Small is better for random access reading.

model:
  input_planes: 69                                   # 68-plane feature stack (P1 pieces, P2 pieces, reps, etc.)
  filters: 128                                       # Convolutional filters (Network "width")
  resblocks: 16                                      # Residual blocks (Network "depth")

data_generation:
  inference_worker_cores:                            # Dedicated CPU cores for the Batching Process (feeding the GPU)
    - [14]
    - [15]
  game_worker_cores: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
  batch_size_per_worker: 4                           # Max positions a single worker sends at once
  batch_size_factor: 10                              # Multiplier to determine max GPU batch size (Workers * Batch * Factor)
  batch_timeout: 0.001                               # How long the GPU batcher waits for more data before running partial batch
  virtual_loss: 0.3                                  # Penalty applied to nodes currently being explored (prevents threads flocking)
  gumbel_c_visit: 50.0                               # Sigma used for gumbel score calucation
  gumbel_c_scale: 1.0                                # Scale for sigma with visit count
  gumbel_noise: 1.0                                  # Gumbel noise value
  gumbel_search_budget: [64,64,64,64]                # Search depth distribution (k = 2^number, search depth = sum)
  temperature_ply_cutoff: 30                         # Sample proportional to visit count for first moves
  temperature_top_move: 0.6                          # Probability the top move is played
  temperature_blunder_threshold: 0.5                 # Threshold for ignoring blunders
  draw_cutoff: -0.5                                  # Value threshold to consider a game a draw (minimax)
  resignation_probability: 0.9                       # Chance the bot checks for resignation allowed
  resignation_cutoff: -0.90                          # Bot resigns to save compute time
  main_logging_level: 20                             # INFO level
  worker_logging_level: 50                           # CRITICAL only (only keeps PGN)
  inference_logging_level: 20                        # INFO level

training:
  batch_size: 4096                                   # Positions per Gradient Update
  sampling_ratio: 2.0                                # Train on x the amount of data generated
  replacement: True                                  # Allow sampling the same position twice in one batch
  policy_loss_weight: 1.0                            # Weight for Move Prediction loss
  value_loss_weight: 1.0                             # Weight for Win/Loss Prediction loss
  weight_decay: 1e-4                                 # L2 Regularization
  lr_high: 1e-1                                      # SGD Learning Rate for different phases of training
  lr_high_cutoff: 1000
  lr_mid: 1e-2
  lr_mid_cutoff: 10000
  lr_low: 1e-3
  momentum_rate: 0.9                                 # SGD Momentum
  data_loader_workers: 1                             # CPU threads loading data from HDF5
  dropout_rate_conv: 0.0                             # Dropout in convolutional layers
  dropout_rate_fc: 0.0                               # Dropout in fully connected head
  dropout_conv_start_block: 10                       # If using dropout, start at block 10
  main_logging_level: 20                             # INFO level