self_play:
  search_depth: 600
  dirichlet_alpha: 0.25
  dirichlet_epsilon: 0.2
  opening_book_path: "/Users/User/Projects/talbot/data/opening_books/Titans.bin"
  opening_min_moves: 8
  opening_max_moves: 12
  value_transition_factor: 0.5
  value_max_transition_move: 40
  value_transition_steepness: 0.1
  temperature_threshold_move: 30
  temperature_high: 0.8
  temperature_low: 0

stored_data:
  positions_per_cycle: 10000
  positions_total: 100000
  buffer_file_path: "/Users/User/Projects/talbot/training/reinforcement/rl_cycles/circular_buffer.hdf5"

talbot:
  model_path: "/Users/User/Projects/talbot/training/reinforcement/best_models/v5_supervised_model.pth"
  input_planes: 68
  filters: 128
  resblocks: 20
  cpuct: 3.0
  batchsize: 32

logging:
  selfplay_main_logging_level: 20
  selfplay_worker_logging_level: 10