game:
  white_player: 'talbotbot'
  white_time_per_move: 4.0
  black_player: 'human'
  black_time_per_move: 4.0
  total_games: 5
  initial_fen: Null

talbot:
  model_path: "/Users/hpdev/Projects/talbot/training/reinforcement/rl_cycles/best_models/best_model.pth"
  input_planes: 68
  filters: 128
  resblocks: 20
  cpuct: 2.0
  batchsize: 16

logging:
  main_logging: True
  main_logging_level: 20