game:
  white_player: 'human'
  white_time_per_move: 5.0
  black_player: 'talbot'
  black_time_per_move: 20.0
  total_games: 5
  initial_fen: 'k1r5/p2R3p/N3p3/4Pp2/6p1/5nP1/5P1P/5K2 b - - 0 1'

talbot:
  model_path: "/Users/User/Projects/talbot/training/supervised/v5_historic_input_channels/model/best_chess_ai_model.pth"
  input_planes: 68
  filters: 128
  resblocks: 20
  cpuct: 5.0
  batchsize: 32

logging:
  local_logging: True
  local_logging_level: 20