game:
  white_player: 'talbotbot'
  black_player: 'human'
  initial_fen: Null

model:
  model_path: 'training/reinforcement/rl_cycles/best_models/best_model.pth'
  input_planes: 68
  filters: 128
  resblocks: 16

evaluation:
  training: False
  inference_worker_cores: 
    - [12, 13, 14, 15]
  batch_size_per_worker: 16
  batch_size_factor: 10
  batch_timeout: 0.001
  cpuct: 1.5
  search_depth: 5000
  virtual_loss: 0.3
  temperature_threshold_move: 0
  temperature_high: 0
  temperature_low: 0
  dirichlet_alpha: 0.0
  dirichlet_epsilon: 0.0
  draw_cutoff: 0.0
  resignation_probability: 0.0
  resignation_cutoff: 0.0
  worker_logging_level: 20
  inference_logging_level: 20