game:
  white_player: 'talbotbot'
  white_time_per_move: 1.0
  black_player: 'human'
  black_time_per_move: 1.0
  total_games: 5
  initial_fen: '1Q6/3k4/8/4K3/8/8/8/8 b - - 15 120'

talbot:
  model_path: "/Users/User/Projects/talbot/training/supervised/v5_historic_input_channels/model/best_chess_ai_model.pth"
  input_planes: 68
  filters: 128
  resblocks: 20
  cpuct: 5.0
  batchsize: 32

logging:
  main_logging: True
  main_logging_level: 20