global:
  model_file: 'D:/Projects/talbot/config/model.yaml'              # Path to the secondary architecture config
  model_path: 'D:/Projects/talbot/rl_dir/models/model'            # Path to best model base name
  log_dir: 'D:/Projects/talbot/logs/local_inference'              # Directory for all engine logs
  main_logging_level: 20                                          # Logging level for the UCI Orchestrator

evaluation:
  main_cores: [3]                                                 # Dedicated CPU cores for the main C++ orchestrator
  game_worker_cores: [5, 6, 7, 8]                                 # Dedicated CPU cores for games

inference:
  inference_worker_cores: [13, 14, 15]                            # Dedicated CPU cores for the Batching Process (dispatcher, collector, filler)
  batch_size: 32                                                  # Max batch size during inference
  batch_size_factor: 8                                            # Multiplier for batch size to determine max slots
  batch_timeout_ms: 10                                            # How long the GPU batcher waits
  logging_interval_sec: 60                                        # Interval for system metrics logging
  logging_level: 20                                               # Logging level for the Batcher Diagnostics

mcts:
  node_pool_size: 10000000                                        # Capacity of the persistent MCTS node pool
  worker_minibatch_size: 32                                       # Max positions sent to batcher at once
  virtual_loss: 0.3                                               # Penalty applied to nodes currently being explored
  contempt: 0.0                                                   # Contempt for playing drawing positions
  gumbel_c_visit: 50.0                                            # Sigma used for gumbel score calculation
  gumbel_c_scale: 1.0                                             # Scale for sigma with visit count
  gumbel_noise: 0.0                                               # 0.0 for deterministic tournament play
  gumbel_search_depth: 10000                                     # Default search depth if GUI doesn't specify
  gumbel_m: 64                                                    # m value for sequential halving
  logging_level: 20                                               # Logging level for MCTS Search and Action Selection
  
selection:
  temperature_ply_cutoff: 6                                       # Sample proportional to visit count for first moves
  temperature_q_decay: 0.02                                       # Absolute Q value [-1, 1] Boltzmann temperature decay
  draw_cutoff: -0.25                                              # Value threshold to consider a game a draw
  resignation_probability: 0.0                                    # Chance the bot checks for resignation allowed
  resignation_cutoff: 0.0                                         # Value head cutoff for resignation