game:
  white_player: 'talbot'
  black_player: 'human'
  initial_fen: Null
  white_perspective: True
  model_path: 'rl_dir/best_models/best_model.pth'

evaluation:
  inference_worker_cores:                            # Dedicated CPU cores for the Batching Process (feeding the GPU)
    - [12, 13, 14, 15]
  batch_size_per_worker: 16                          # Max positions a single worker sends at once
  batch_size_factor: 10                              # Multiplier to determine max slots available in RAM
  batch_timeout: 0.005                               # How long the GPU batcher waits for more data before running partial batch
  virtual_loss: 0.3                                  # Penalty applied to nodes currently being explored (prevents threads flocking)
  gumbel_c_visit: 50.0                               # Sigma used for gumbel score calucation
  gumbel_c_scale: 1.0                                # Scale for sigma with visit count
  gumbel_noise: 0.0                                  # Gumbel noise value
  gumbel_search_depth: 10000                         # Search depth budget
  gumbel_m: 32                                       # m value for sequential halving (top m moves sampled)
  temperature_ply_cutoff: 0                          # Sample proportional to visit count for first moves
  temperature_top_move: 0.5                          # Probability the top move is played
  temperature_blunder_threshold: 0.1                 # Threshold for ignoring blunders
  minimax_smoothing_factor: 0.0                      # Smooth minimax with standard MCTS distribution for forcing moves
  draw_cutoff: -0.5                                  # Value threshold to consider a game a draw
  max_ply_length: 0                                  # Hard cutoff to force a draw
  resignation_probability: 0.0                       # Chance the bot checks for resignation allowed
  resignation_cutoff: 0.0                            # Value head cutoff for resignation
  main_logging_level: 20                             # INFO level
  worker_logging_level: 20                           # CRITICAL only (only keeps PGN)
  batcher_logging_level: 20                        # INFO level
