global:
  total_training_steps: 80000                        # Total gradient updates to perform
  logging_rotation_steps: 1000                       # How often to make a new log folder
  min_buffer_size: 1024000                           # Minimum replay buffer size
  max_buffer_size: 24576000                          # Max buffer size
  buffer_ramp_steps: 30000                           # Steps to reach max buffer size (linear)
  min_build_steps: 200                               # Minimum steps for a new engine build
  max_build_steps: 1000                              # Max steps for a new engine build
  build_ramp_steps: 10000                            # Steps to reach max engine build rate (linear)
  model_path: 'rl_dir/models/model'                  # Path to best model base name

inference:
  inference_worker_cores: [8, 9, 10]               # Dedicated CPU cores for the Batching Process (feeding the GPU)
  batch_size: 512                                    # Max batch size during inference
  batch_size_factor: 12                              # Multiplier for batch size to determine max slots available in RAM
  batch_timeout_ms: 10                               # How long the GPU batcher waits for more data before running partial batch
  logging_interval_sec: 60
  logging_level: 20

data_generation:
  data_generator_cores: [3]                          # Dedicated CPU cores for the main C++ orchestrator and data generator task
  io_write_cores: [4]
  game_worker_cores: [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
  workers_per_core: 10                               # Number of game workers to pin to each core
  max_ply_length: 400                                # Hard cutoff to force a draw  main_logging_level: 20
  main_logging_level: 20
  worker_logging_level: 50
  io_logging_level: 20

mcts:
  node_pool_size: 50000                              # Capacity of the persistent MCTS node pool
  worker_minibatch_size: 16                          # Max positions a single worker sends at once
  virtual_loss: 0.3                                  # Penalty applied to nodes currently being explored (prevents threads flocking)
  gumbel_c_visit: 50.0                               # Sigma used for gumbel score calculation
  gumbel_c_scale: 1.0                                # Scale for sigma with visit count
  gumbel_noise: 1.0                                  # Gumbel noise value
  gumbel_search_depth: 128                           # Search depth budget
  gumbel_m: 16                                       # m value for sequential halving (top m moves sampled)
  minimax_target_override: True
  minimax_win_target: 0.95
  minimax_loss_target: 0.001

selection:
  temperature_ply_cutoff: 30                         # Sample proportional to visit count for first moves
  temperature_q_decay: 0.1                           # Absolute Q value [-1, 1] Boltazmann temperature decay
  draw_cutoff: 0.0                                   # Value threshold to consider a game a draw
  resignation_probability: 0.9                       # Chance the bot checks for resignation allowed
  resignation_cutoff: -0.80                          # Value head cutoff for resignation

training:
  training_cores: [5]                                # Dedicated CPU cores for training task
  io_read_cores: [6, 7]                              # Dedicated CPU cores for batch prefetching
  prefetch_workers: 8                                # How many workers in async read process to query lmdb
  seed: 42                                           # Seed for initialisation
  batch_size: 4096                                   # Positions per Gradient Update
  sampling_ratio: 1.0                                # Train on x the amount of data generated
  replacement: True                                  # Allow sampling the same position twice in one batch
  policy_loss_weight: 1.0                            # Weight for Move Prediction loss
  value_loss_weight: 1.0                             # Weight for Win/Loss Prediction loss
  weight_decay: 1e-4                                 # L2 Regularization
  learning_rate: 1e-1                                # SGD Learning Rate
  momentum_rate: 0.9                                 # SGD Momentum
  logging_level: 20